# Generated by Django 5.2 on 2025-04-19 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('career', 'Career'), ('study', 'Study'), ('social', 'Social Media'), ('coding', 'Coding'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
