# Generated by Django 5.2 on 2025-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_category_prompt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags like ai, productivity, writing', max_length=200),
        ),
    ]
